export type CategoryGroup = {
  label: string;
  categories: string[];
};

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    label: "Pan, alimentos frescos y preparados",
    categories: [
      "Panadería",
      "Pastelería y repostería",
      "Frutas y verduras",
      "Carnes",
      "Pollo y pavo",
      "Pescados y mariscos",
      "Comida preparada",
      "Huevos",
    ],
  },
  {
    label: "Fiambrería, lácteos y refrigerados",
    categories: [
      "Leches",
      "Yogures",
      "Quesos",
      "Jamones y fiambres",
      "Mantequillas y margarinas",
      "Postres refrigerados",
      "Productos vegetales refrigerados",
    ],
  },
  {
    label: "Mercadería y abarrotes",
    categories: [
      "Arroz, pastas y legumbres",
      "Aceites y vinagres",
      "Harinas y repostería",
      "Conservas",
      "Salsas y condimentos",
      "Sopas y caldos",
      "Cereales y avena",
      "Café, té y cacao",
      "Azúcar y endulzantes",
      "Alimentos para bebé",
      "Productos sin gluten",
    ],
  },
  {
    label: "Bebidas, golosinas y picoteo",
    categories: [
      "Bebidas gaseosas",
      "Aguas",
      "Jugos y néctares",
      "Bebidas energéticas e isotónicas",
      "Cervezas",
      "Vinos y espumantes",
      "Licores",
      "Papas fritas y snacks salados",
      "Galletas",
      "Chocolates y confites",
      "Helados",
      "Frutos secos y barras",
    ],
  },
  {
    label: "Congelados y hielo",
    categories: [
      "Congelados",
      "Pizzas y masas congeladas",
      "Verduras congeladas",
      "Hamburguesas y proteínas congeladas",
    ],
  },
  {
    label: "Higiene personal y cuidado de guagua",
    categories: [
      "Papel higiénico y pañuelos",
      "Jabones",
      "Shampoo y cuidado capilar",
      "Higiene dental",
      "Desodorantes",
      "Cuidado femenino",
      "Pañales y cuidado infantil",
      "Afeitado",
      "Protección solar",
    ],
  },
  {
    label: "Aseo, hogar y desechables",
    categories: [
      "Detergentes para ropa",
      "Lavalozas",
      "Limpiadores y desinfectantes",
      "Cloro",
      "Esponjas, paños y guantes",
      "Bolsas de basura",
      "Papel absorbente y servilletas",
      "Insecticidas",
      "Ambientadores",
      "Desechables y envases",
      "Artículos de cocina",
    ],
  },
  {
    label: "Mascotas, bazar, tabaco y servicios",
    categories: [
      "Alimentos para perros",
      "Alimentos para gatos",
      "Accesorios para mascotas",
      "Librería y útiles escolares",
      "Pilas y artículos eléctricos",
      "Ferretería básica",
      "Juguetes",
      "Recargas y servicios",
      "Tabaco y accesorios",
      "Otros",
    ],
  },
];

export const ALL_CATEGORIES = CATEGORY_GROUPS.flatMap((group) => group.categories);

const CATEGORY_LABELS: Record<string, string> = {
  "Panadería": "Pan, panadería y masas",
  "Pastelería y repostería": "Pastelería, tortas y repostería",
  "Frutas y verduras": "Frutas, verduras y hortalizas",
  "Carnes": "Carnes y carnicería",
  "Pollo y pavo": "Pollo, pavo y otras aves",
  "Pescados y mariscos": "Pescados y mariscos",
  "Comida preparada": "Comida preparada, sándwiches y colaciones",
  "Huevos": "Huevos",
  "Leches": "Leche y bebidas lácteas",
  "Yogures": "Yogur y yogures",
  "Quesos": "Quesos",
  "Jamones y fiambres": "Jamón, cecinas y fiambres",
  "Mantequillas y margarinas": "Mantequilla y margarina",
  "Postres refrigerados": "Postres, flanes y gelatinas refrigeradas",
  "Productos vegetales refrigerados": "Alternativas vegetales refrigeradas",
  "Arroz, pastas y legumbres": "Arroz, tallarines, pastas y legumbres",
  "Aceites y vinagres": "Aceites y vinagres",
  "Harinas y repostería": "Harinas, premezclas y repostería",
  "Conservas": "Conservas y enlatados",
  "Salsas y condimentos": "Salsas, condimentos y aliños",
  "Sopas y caldos": "Sopas, caldos y tallarines instantáneos",
  "Cereales y avena": "Cereales, avena y granola",
  "Café, té y cacao": "Café, té, mate y chocolate en polvo",
  "Azúcar y endulzantes": "Azúcar, sal y endulzantes",
  "Alimentos para bebé": "Alimentos, colados y picados para guagua",
  "Productos sin gluten": "Sin gluten y alimentación especial",
  "Bebidas gaseosas": "Bebidas gaseosas y refrescos",
  "Aguas": "Agua mineral, purificada y saborizada",
  "Jugos y néctares": "Jugos, néctares y bebidas en polvo",
  "Bebidas energéticas e isotónicas": "Energéticas, isotónicas y deportivas",
  "Cervezas": "Cervezas",
  "Vinos y espumantes": "Vinos, espumantes y chicha",
  "Licores": "Pisco, licores y destilados",
  "Papas fritas y snacks salados": "Papas fritas, ramitas y snacks salados",
  "Galletas": "Galletas dulces y saladas",
  "Chocolates y confites": "Chocolates, dulces y confites",
  "Helados": "Helados y paletas",
  "Frutos secos y barras": "Frutos secos, barras, cabritas y picoteo",
  "Congelados": "Hielo y otros congelados",
  "Pizzas y masas congeladas": "Pizzas, empanadas y masas congeladas",
  "Verduras congeladas": "Frutas y verduras congeladas",
  "Hamburguesas y proteínas congeladas": "Hamburguesas, carnes y proteínas congeladas",
  "Papel higiénico y pañuelos": "Confort, papel higiénico y pañuelos",
  "Jabones": "Jabones y alcohol gel",
  "Shampoo y cuidado capilar": "Shampoo y cuidado del pelo",
  "Higiene dental": "Pasta dental, cepillos e higiene bucal",
  "Desodorantes": "Desodorantes",
  "Cuidado femenino": "Toallas higiénicas y cuidado femenino",
  "Pañales y cuidado infantil": "Pañales y cuidado de guagua",
  "Afeitado": "Afeitado y depilación",
  "Protección solar": "Bloqueador y protección solar",
  "Detergentes para ropa": "Detergentes y suavizantes para ropa",
  "Lavalozas": "Lavaloza y productos para vajilla",
  "Limpiadores y desinfectantes": "Limpiadores, desinfectantes y sanitizantes",
  "Cloro": "Cloro y blanqueadores",
  "Esponjas, paños y guantes": "Esponjas, paños, virutillas y guantes",
  "Bolsas de basura": "Bolsas de basura",
  "Papel absorbente y servilletas": "Toalla nova, papel absorbente y servilletas",
  "Insecticidas": "Insecticidas y control de plagas",
  "Ambientadores": "Aromatizantes y ambientadores",
  "Desechables y envases": "Desechables, envases y cotillón",
  "Artículos de cocina": "Utensilios y artículos de cocina",
  "Alimentos para perros": "Comida para perros",
  "Alimentos para gatos": "Comida para gatos",
  "Accesorios para mascotas": "Accesorios y arena para mascotas",
  "Librería y útiles escolares": "Librería, útiles escolares y fotocopias",
  "Pilas y artículos eléctricos": "Pilas, ampolletas y artículos eléctricos",
  "Ferretería básica": "Ferretería y gasfitería básica",
  "Juguetes": "Juguetes y regalos",
  "Recargas y servicios": "Recargas, pago de cuentas y servicios",
  "Tabaco y accesorios": "Cigarrillos, tabaco y accesorios",
  "Otros": "Otros productos",
};

const CATEGORY_ALIASES: Record<string, string[]> = {
  "Panadería": ["pan corriente", "hallulla", "marraqueta", "pan batido"],
  "Comida preparada": ["completos", "sandwich", "sánguche", "colacion", "colación"],
  "Leches": ["leche larga vida", "leche uht"],
  "Jamones y fiambres": ["cecinas", "vienesas", "longanizas", "salame", "mortadela"],
  "Arroz, pastas y legumbres": ["tallarines", "fideos", "porotos", "lentejas", "garbanzos"],
  "Conservas": ["enlatados", "jurel", "atun", "atún"],
  "Salsas y condimentos": ["aliños", "merken", "merkén", "mayonesa", "ketchup"],
  "Sopas y caldos": ["sopaipillas instantaneas", "ramen", "fideos instantaneos"],
  "Café, té y cacao": ["mate", "chocolate caliente"],
  "Alimentos para bebé": ["guagua", "colado", "picado"],
  "Bebidas gaseosas": ["bebida", "gaseosa", "refresco"],
  "Aguas": ["agua mineral", "agua purificada"],
  "Jugos y néctares": ["jugo en polvo"],
  "Licores": ["pisco", "ron", "vodka", "whisky", "aguardiente"],
  "Papas fritas y snacks salados": ["ramitas", "sufles", "suflé", "doritos", "cheetos"],
  "Chocolates y confites": ["dulces", "calugas", "gomitas", "chicles"],
  "Frutos secos y barras": ["cabritas", "mani", "maní", "picoteo"],
  "Congelados": ["hielo", "cubos de hielo"],
  "Papel higiénico y pañuelos": ["confort"],
  "Pañales y cuidado infantil": ["guagua", "toallitas humedas", "toallitas húmedas"],
  "Lavalozas": ["lavaloza", "quix"],
  "Esponjas, paños y guantes": ["virutilla"],
  "Papel absorbente y servilletas": ["toalla nova", "nova"],
  "Desechables y envases": ["vasos plasticos", "vasos plásticos", "platos", "cotillon", "cotillón"],
  "Alimentos para perros": ["comida perro", "pellet perro"],
  "Alimentos para gatos": ["comida gato", "pellet gato"],
  "Pilas y artículos eléctricos": ["ampolletas", "enchufes"],
  "Ferretería básica": ["gasfiteria", "gasfitería", "huincha aisladora"],
  "Recargas y servicios": ["carga bip", "recarga celular", "pago de cuentas"],
  "Tabaco y accesorios": ["cigarros", "cigarrillos", "encendedores"],
};

const normalizeSearchText = (value: string) =>
  value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es");

export function categoryDisplayName(category: string): string {
  return CATEGORY_LABELS[category] || category;
}

export function categoryMatchesSearch(category: string, query: string): boolean {
  const searchable = [
    category,
    categoryDisplayName(category),
    ...(CATEGORY_ALIASES[category] || []),
  ].join(" ");
  return normalizeSearchText(searchable).includes(normalizeSearchText(query));
}

const CATEGORY_RULES: Array<[string[], string]> = [
  [["cheese", "queso"], "Quesos"],
  [["ham", "prosciutto", "salami", "sausage", "fiambre", "jamon", "jamón"], "Jamones y fiambres"],
  [["yogurt", "yoghurt", "yogur"], "Yogures"],
  [["milk", "leche"], "Leches"],
  [["bread", "bakery", "pan"], "Panadería"],
  [["cookie", "biscuit", "galleta"], "Galletas"],
  [["chocolate", "candy", "confection", "confite"], "Chocolates y confites"],
  [["chip", "crisp", "snack"], "Papas fritas y snacks salados"],
  [["water", "agua"], "Aguas"],
  [["juice", "nectar", "jugo"], "Jugos y néctares"],
  [["soda", "soft-drink", "carbonated", "bebida"], "Bebidas gaseosas"],
  [["beer", "cerveza"], "Cervezas"],
  [["wine", "vino"], "Vinos y espumantes"],
  [["ice-cream", "helado"], "Helados"],
  [["coffee", "tea", "cocoa", "café"], "Café, té y cacao"],
  [["rice", "pasta", "legume", "arroz"], "Arroz, pastas y legumbres"],
  [["oil", "vinegar", "aceite"], "Aceites y vinagres"],
  [["cereal", "oat", "avena"], "Cereales y avena"],
  [["sauce", "condiment", "salsa"], "Salsas y condimentos"],
  [["frozen", "congelado"], "Congelados"],
  [["pet-food", "dog-food"], "Alimentos para perros"],
  [["cat-food"], "Alimentos para gatos"],
  [["shampoo", "hair-care"], "Shampoo y cuidado capilar"],
  [["soap", "jabón", "jabon"], "Jabones"],
  [["tooth", "dental"], "Higiene dental"],
  [["deodorant"], "Desodorantes"],
  [["diaper", "pañal"], "Pañales y cuidado infantil"],
  [["detergent", "laundry"], "Detergentes para ropa"],
  [["dishwashing", "lavaloza"], "Lavalozas"],
  [["cleaner", "disinfect", "limpiador"], "Limpiadores y desinfectantes"],
  [["toilet-paper", "tissue"], "Papel higiénico y pañuelos"],
];

export function inferCategory(tags: string[] = [], productName = ""): string {
  const searchable = `${tags.join(" ")} ${productName}`.toLocaleLowerCase("es");
  const match = CATEGORY_RULES.find(([keywords]) =>
    keywords.some((keyword) => searchable.includes(keyword)),
  );
  return match?.[1] || "Otros";
}
